{% set name = "curies" %}
{% set version = "0.7.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/curies-{{ version }}.tar.gz
  sha256: d3aaf16644b26ac2605ff83c565ec7df0ba0b5f7425516047666e609ec5fb718

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pytrie
    - pydantic
    - requests

test:
  imports:
    - curies
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cthoyt/curies
  summary: Idiomatic conversion between URIs and compact URIs (CURIEs).
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isuruf
    - dillonroach
